Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 30
Metrics/ClassLength:
  Max: 1500
Metrics/BlockLength:
  Max: 75
Metrics/CyclomaticComplexity:
  Max: 9
Style/Documentation:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false
Style/FrozenStringLiteralComment:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
